name: Spacegame.Web
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  BUILD:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$GITHUB_WORKSPACE/TestResults/Coverage/      

    # - name: SonarCloud Scan
    #   uses: sonarsource/sonarcloud-github-action@v1.1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: space-web
        path: ./Tailspin.SpaceGame.Web/obj/Release/netcoreapp3.1

#---------------
  DEPLOY:
    name: Deploy
    runs-on: ubuntu-latest
    needs: BUILD
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: space-web 
 
    - name: Display structure of downloaded files
      run: ls -R
    
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: heyyworld
        publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
        package: ./space-web
